spring:
  application:
    name: currency-rate-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/currencydb
    username: currency
    password: currency

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/currencydb
    user: currency
    password: currency

  sql:
    init:
      mode: never

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: INFO
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

rates:
  fiat:
    base-url: http://localhost:8080/fiat-currency-rates
    api-header: X-API-KEY
    api-key: secret-key
  crypto:
    base-url: http://localhost:8080/crypto-currency-rates
  http:
    timeout: 3s
    max-in-memory-size: 1MB
    wiretap-enabled: false
